export const permissionCatalog = [
  { module: 'companies', action: 'read', name: 'View companies' },
  { module: 'companies', action: 'create', name: 'Create companies' },
  { module: 'companies', action: 'update', name: 'Update companies' },
  { module: 'companies', action: 'delete', name: 'Deactivate companies' },
  { module: 'companies', action: 'activate', name: 'Activate companies' },
  { module: 'companies', action: 'backup', name: 'Back up companies' },
  { module: 'companies', action: 'restore', name: 'Restore company backups' },
  { module: 'users', action: 'read', name: 'View users' },
  { module: 'users', action: 'create', name: 'Create users' },
  { module: 'users', action: 'update', name: 'Update users' },
  { module: 'users', action: 'delete', name: 'Deactivate users' },
  { module: 'users', action: 'reset-password', name: 'Reset user passwords' },
  { module: 'users', action: 'activity-log', name: 'View user activity' },
  { module: 'roles', action: 'read', name: 'View roles and permissions' },
  { module: 'roles', action: 'create', name: 'Create roles' },
  { module: 'roles', action: 'update', name: 'Update roles' },
  { module: 'roles', action: 'delete', name: 'Delete roles' },
  { module: 'roles', action: 'assign-permissions', name: 'Assign permissions' },
] as const;
